# Basic configuration
baseURL = 'https://tokyoindies.com/'
languageCode = 'ja-jp'
title = 'Tokyo Indies'
theme = 'hugo-bearcub'
copyright = "© Tokyo Indies"
DefaultContentLanguage = 'ja'

# add for reading time
hasCJKLanguage = true

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
[languages.ja]
title = "Tokyo Indies"
languageName = '日本語'
contentDir = 'content/ja'
weight = 1
[languages.ja.params]
madeWith = "Made in [Bear Cub](https://github.com/clente/hugo-bearcub)"
# [languages.ja.pagination]
# disableAliases = false
# pagerSize = 12
# path = 'page'

[languages.en]
title = "Tokyo Indies"
languageName = 'English'
contentDir = 'content/en'
weight = 2
[languages.en.params]
madeWith = "Made in [Bear Cub](https://github.com/clente/hugo-bearcub)"
# [languages.en.pagination]
# disableAliases = false
# pagerSize = 12
# path = 'page'

# RSS settings
[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]

[params]
# The description of your website
description = "東京インディーズは、月1で個人ゲーム開発者を集まって、お互いのゲームを見せ合ったり意見交換をするのが目的のゆる～い交流会です。Tokyo Indies is a monthly gathering in central Tokyo for anyone interested in game development."
# The path to your favicon
favicon = "favicon.ico"

# These images will show up when services want to generate a preview of a link
# to your site. Ignored if `generateSocialCard = true`. For more information
# about previews, see https://gohugo.io/templates/internal#twitter-cards and
# https://gohugo.io/templates/internal#open-graph
images = ["tokyo-indies-banner.png"]

# This title is used as the site_name on the Hugo's internal opengraph
# structured data template
title = 'Tokyo Indies'

# Dates are displayed following the format below. For more information about
# formatting, see https://gohugo.io/functions/format/
dateFormat = "2006/01/02"

# If your blog is multilingual but you haven't translated a page, this theme
# will create a disabled link. By setting `hideUntranslated` to true, you can
# have the theme simply not show any link
hideUntranslated = false

# (EXPERIMENTAL) This theme has two options for its CSS styles: "original" and
# "herman". The former is what you see on Bear Cub's demo (an optimized
# version of Hugo Bear Blog), while the latter has a more modern look based on
# Herman Martinus's version of the Blogster Minimal theme for Astro.
themeStyle = "original"

# (EXPERIMENTAL) This theme is capable of dynamically generating social cards
# for posts that don't have `images` defined in their front matter; By setting
# `generateSocialCard` to false, you can prevent this behavior. For more
# information see layouts/partials/social_card.html
generateSocialCard = false

# Social media. Delete any item you aren't using to make sure it won't show up
# in your website's metadata.
[params.social]
twitter = "tokyo_indies"

# Author metadata. This is mostly used for the RSS feed of your site, but the
# email is also added to the footer of each post. You can hide the "reply to"
# link by using a `hideReply` param in front matter.
[params.author]
name = "Tokyo Indies"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# disable smart quotes
[markup.goldmark.extensions.typographer]
disable = false
apostrophe = '&apos;'
ellipsis = '&#46;&#46;&#46;'
emDash = '&mdash;'
enDash = '&ndash;'
rightDoubleQuote = '&quot;'
leftDoubleQuote = '&quot;'
rightSingleQuote = '&apos;'
leftSingleQuote = '&apos;'
rightAngleQuote = '&rsaquo;'
leftAngleQuote = '&lsaquo;'


SectionPagesMenu = 'main'

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/tokyo_indies"

# [[params.ananke_socials]]
# name = "bluesky"
# url = "https://bsky.app/profile/tokyoindies.com"

# [[params.ananke_socials]]
# name = "discord"
# url = "https://discord.com/invite/NZaHDmUXpM"

# [[params.ananke_socials]]
# name = "twitch"
# url = "https://www.twitch.tv/tokyo_indies"

# [[params.ananke_socials]]
# name = "steam"
# url = "https://store.steampowered.com/curator/45232922-Tokyo-Indies/"
