baseURL = 'https://tokyoindies.com/'
languageCode = 'ja-jp'
title = 'Tokyo Indies'
theme = 'ananke'
SectionPagesMenu = 'main'

DefaultContentLanguage = 'ja'
languageName = '日本語'

[params]
 custom_css = ["indies.css"]

[languages]
  [languages.ja]
    contentDir = 'content/ja'
    languageName = '日本語'
    weight = 1
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 2

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/tokyo_indies"

[[params.ananke_socials]]
name = "discord"
url = "https://discord.gg/asobu"

[[params.ananke_socials]]
name = "twitch"
url = "https://www.twitch.tv/asobudev"
